version: "3.3"

services: 
    frontend: 
        container_name: frontend
        image: adityaudi/app-frontend:v2.0.0.1
        ports: 
            - "80:80"
            - "443:443"
        networks:
            - networkid
        environment:
            - VUE_APP_URL=http://nodejs:80/product
            - VUE_APP_URL_HISTORY=http://nodejs:80/history
            - VUE_APP_URL_USERS=http://nodejs:80/users
            - VUE_APP_URL_AUTH=http://nodejs:80/auth

networks:
    networkid:
